version: '3.8'
services:
  fastapi:
    build: .
    container_name: notesapp_fastapi
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: to-do-app
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    networks:
      - notesapp_network

  db:
    image: postgres:13
    container_name: notesapp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: to-do-app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - notesapp_network

  redis:
    image: redis:alpine
    container_name: notesapp_redis
    ports:
      - "6379:6379"
    networks:
      - notesapp_network

  streamlit:
    image: aminehy/docker-streamlit-app:latest
    container_name: notesapp_streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run appui.py
    depends_on:
      - fastapi
      - db
      - redis
    networks:
      - notesapp_network

volumes:
  postgres_data:

networks:
  notesapp_network:
