version: '3.8'

services:
  fastapi:
    build: .
    container_name: notesapp_fastapi
    ports:
      - "8000:8000"
    environment:
      DB_USER: postgres
      DB_PASSWORD: root
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: to-do-app
    depends_on:
      - db
      - redis
    volumes:
      - .:/app

  db:
    image: postgres:13
    container_name: notesapp_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: to-do-app
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:alpine
    container_name: notesapp_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
